spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:root}
    password: ${RABBITMQ_PASSWORD:}

rabbitmq:
  queue-name: ${RABBITMQ_QUEUE_NAME:queue}
  exchange-name: ${RABBITMQ_EXCHANGE_NAME:exchange}
  routing-key: ${RABBITMQ_ROUTING_KEY:key}

mail:
  reset-password:
    link: ${RESET_PASSWORD_LINK}
  admin:
    email: ${ADMIN_EMAIL}

oauth2:
  naver:
    tokenUri: https://nid.naver.com/oauth2.0/token
    clientId: ${NAVER_CLIENT_ID}
    clientSecret: ${NAVER_CLIENT_SECRET}
    redirectUri: ${NAVER_REDIRECT_URI}
    userInfoUri: https://openapi.naver.com/v1/nid/me

  kakao:
    tokenUri: https://kauth.kakao.com/oauth/token
    clientId: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirectUri: ${KAKAO_REDIRECT_URI}
    userInfoUri: https://kapi.kakao.com/v2/user/me
    issuer: https://kauth.kakao.com

  apple:
    tokenUri: https://appleid.apple.com/auth/token
    clientId: ${APPLE_CLIENT_ID}
    redirectUri: ${APPLE_REDIRECT_URI}
    userInfoUri: https://appleid.apple.com/auth/token
    issuer: https://appleid.apple.com
    teamId: ${APPLE_TEAM_ID}
    keyId: ${APPLE_KEY_ID}
    privateKey: ${APPLE_KEY}

cache:
  ttl:
    default: ${CACHE_TTL:30}
    apple-client-secret: ${CLIENT_SECRET_TTL:15552000}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
    model: ${OPENAI_API_MODEL}

firebase:
  key: ${FIREBASE_KEY}