spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:}

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.naver.com

mail:
  reset-password:
    link: ${RESET_PASSWORD_LINK}
  admin:
    email: ${ADMIN_EMAIL}

oauth2:
  kakao:
    tokenUri: https://kauth.kakao.com/oauth/token
    clientId: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirectUri: ${KAKAO_REDIRECT_URL}
    userInfoUri: https://kapi.kakao.com/v2/user/me

  naver:
    tokenUri: https://nid.naver.com/oauth2.0/token
    clientId: ${NAVER_CLIENT_ID}
    clientSecret: ${NAVER_CLIENT_SECRET}
    redirectUri: ${NAVER_REDIRECT_URL}
    userInfoUri: https://openapi.naver.com/v1/nid/me

cache:
  ttl:
    default: ${CACHE_TTL:30}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
    model: ${OPENAI_API_MODEL}