name: Deploy - Combined

on:
  push:
    branches: [ "main" ]

jobs:
  determine-modules:
    runs-on: ubuntu-latest
    outputs:
      deployApis: ${{ steps.set.outputs.deployApis }}
      deployAdmin: ${{ steps.set.outputs.deployAdmin }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changes
        run: |
          git fetch origin main
          CHANGED=$(git diff --name-only origin/main...HEAD)
          echo "$CHANGED" > changed.txt

      - name: Decide what to deploy
        id: set
        run: |
          CHANGED=$(cat changed.txt)

          echo "Changed files:"
          echo "$CHANGED"

          DEPLOY_APIS=false
          DEPLOY_ADMIN=false

          for file in $CHANGED; do
            if [[ "$file" == yournews-apis/* ]]; then
              DEPLOY_APIS=true
            elif [[ "$file" == yournews-admin/* ]]; then
              DEPLOY_ADMIN=true
            elif [[ "$file" == yournews-auth/* || "$file" == yournews-common/* || "$file" == yournews-domain/* || "$file" == yournews-infra/* ]]; then
              DEPLOY_APIS=true
              DEPLOY_ADMIN=true
              break
            fi
          done

          echo "deployApis=$DEPLOY_APIS" >> $GITHUB_OUTPUT
          echo "deployAdmin=$DEPLOY_ADMIN" >> $GITHUB_OUTPUT

  deploy-apis:
    needs: determine-modules
    if: needs.determine-modules.outputs.deployApis == 'true'
    uses: ./.github/workflows/deploy-apis.yml
    secrets: inherit

  deploy-admin:
    needs: determine-modules
    if: needs.determine-modules.outputs.deployAdmin == 'true'
    uses: ./.github/workflows/deploy-admin.yml
    secrets: inherit