name: Deploy - admin

on:
  workflow_dispatch:
  # 다른 워크플로에서 호출 가능하게 하기 위한 트리거
  workflow_call:

jobs:
  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      # 1. push된 커밋 기준 코드 내려 받기
      - name: Checkout PR
        uses: actions/checkout@v3

      # 2. 자바 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build Gradle
      - name: Build admin
        run: |
          chmod +x ./gradlew
          ./gradlew :yournews-admin:build -x test

      # 4. 현재 커밋의 짧은 SHA 값을 가져와 VERSION 환경변수로 등록
      - name: Set VERSION from short SHA
        id: version
        run: |
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 5. Docker 이미지 build 및 push
      - name: Docker Build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yournews-admin:$VERSION ./yournews-admin
          docker tag ${{ secrets.DOCKER_USERNAME }}/yournews-admin:$VERSION ${{ secrets.DOCKER_USERNAME }}/yournews-admin:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/yournews-admin:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/yournews-admin:latest

      # 6. AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 7. AWS CLI 설치
      - name: Install AWS CLI
        run: |
          curl -sS https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      # 8. SSM Run Command로 EC2 배포 스크립트 실행
      - name: Deploy with SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy yournews-admin via GitHub Actions" \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --region ap-northeast-2 \
            --parameters commands='bash /home/ubuntu/script/admin_deploy.sh' \
            --output text
